apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: lrbackend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: { { .Values.frontend.containerPort } }
  type: { { .Values.frontend.service.type } }
